### ISSUE TITLE
Exception error on enum 7 for HoldingType

### ISSUE THREAD

**Issue by waltwj** [lrimkus/tradeking-api-consumer#1]
Hi, I found your tradeking  API and I thought I'd see if I could get it to work for me.  I'm able to connect to my account and the exception message shows all sorts of account information related to my account, which tells me it's talking to tradeking. However it seems to be getting an exception on a HoldingType of value 7.  The enum currently has these 3 types listed:  CASH(1), MARGIN_LONG(2), MARGIN_SHORT(5)

Exception in thread "main" org.springframework.http.converter.HttpMessageNotReadableException: Could not read JSON: Can not construct instance of com.miserablemind.api.consumer.tradeking.api.domain.account.holdings.AccountHoldingEntry$HoldingType from String value '7': value not one of declared Enum instance names: [1, 2, 5]

**Comment by lrimkus** [comment]
hi, thanks for reporting.  I will check it out.  At the same time I also accept pull requests :)

https://www.ally.com/api/invest/documentation/accounts-id-holdings-get/ docs do not provide what it is, i guess we can set it to UNKNOWN as it seems forums are gone after ally take over.

**Comment by waltwj** [comment]
LOL, I already tried adding the "UKNOWN(7)" to the enum "HoldingType". But I get the same error. I have to confess I'm new to GitHub and java. Sorry for being such a noob at this.

Because I'm such a noob, if you don't mind, can you explain why I'd want to do pulls?

**Comment by lrimkus** [comment]
So I fixed this one, tested it should work. Actually once you get the object there is holding display data which gives you a description of what actually it is. 

pull request would be you fixing it and asking to merge in your changes.
